### ISSUE TITLE
support for uma0://

### ISSUE THREAD

**Issue by taneofpain** [meetpatty/basiliskii-vita#5]
Would love it if you would add support for uma0:// in addition to ux0://

**Comment by meetpatty** [comment]
Hi,

Can you try the below version, I have no way of testing locally. Expects files to be in uma0:data/BasiliskII. Also it takes preference of ux0: over uma0: so remove/rename ux0:data/BasiliskII.

[BasiliskII.zip](https://github.com/meetpatty/basiliskii-vita/files/1480397/BasiliskII.zip)

**Comment by taneofpain** [comment]
Thank you very much. This works great.  I'm new to the vita port - it boots (os 8) fine and runs (tested dark castle 3) with sound. The only thing i haven't figured out is how to use the touchscreen in the back. Is that enabled by default or is there options for it.  Thanks again brings back memories of my youth ;).
________________________________
